### ISSUE TITLE
Settings Tab

### ISSUE THREAD

**Issue by learning2makethings** [learning2makethings/HapticTouch#23]
Do we want a tab bar to hold a settings view to toggle items such as the issues below? Create a settings button somewhere else?  Let me know your ideas. https://github.com/learning2makethings/HapticTouch/issues/19
https://github.com/learning2makethings/HapticTouch/issues/3

**Comment by jassler** [comment]
I think a tab bar would make sense if we have more than 2 tabs - so besides Metronome and Settings we could maybe think about more stuff to add? A tuner would be possible, don't know how difficult this is, but it would be an exciting challenge (to me at least).

Otherwise I'd just propose having a settings "gearwheel" at the top.
![sth like this](https://www.iconfinder.com/icons/1240529/cog_configuration_gear_preferences_settings_setup_wheel_icon)

**Comment by learning2makethings** [comment]
Works for me. I bought some icons a loooong time ago and it has a handful of gear icons. I'll add that icon into the navcon in the top right.
